---
title: "Simple document"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to import data.

## Import the FAS Litters CSV
```{r}
litters_df = read_csv("data/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)
```

```{r}
view(litters_df)
head(litters_df)
```

```{r}
litters_df = 
    read_csv(file = "./data/FAS_litters.csv",
    skip = 10, col_names = FALSE)
litters_df
```

```{r}
litters_df = 
    read_csv(
        file = "./data/FAS_litters.csv",
        na = c(".", "NA", ""))
litters_df
litters_df = janitor::clean_names(litters_df)

pull(litters_df, gd0_weight)
```

```{r}
litters_df = 
    read_csv(
        file = "./data/FAS_litters.csv",
        na = c(".", "NA", ""),
        col_types = cols(
          Group = col_factor()
        )
    )
```

Import the FAS pups CSV
```{r}
pups_df = read_csv(file = "./data/FAS_pups.csv")

```

Import MLB 2011 summary data
```{r}
mlb_df = read_excel("data/mlb11.xlsx", sheet = "mlb11", range = "C1:E7")
```

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_df, 5)
```


## pivot longer
```{r}
pulse_df = 
  read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
```

This need to go from wide to long format
```{r}
pulse_tidy_df =
  pulse_df |>
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |>
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) |>
   relocate(id, visit)
 
```

```{r}
litters_df = 
  read_csv(
        file = "./data/FAS_litters.csv",
        na = c(".", "NA", "")) |>
  litters_df = janitor::clean_names() |>
  pivot_longer(
    cols = gd0_weight : gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  ) |>
  mutate(
    gd_weight = case_match(
      gd_weight,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )

```


## pivot wider
```{r}
analysis_df =
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )
analysis_df
```

```{r}
analysis_df |>
  pivot_wider(
    names_from = time,
    values_from = mean
  ) |>
  knitr::kable()

```

